# Generated by Django 5.0.6 on 2024-05-27 06:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.URLField()),
                ('page_links', models.JSONField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
